In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [2]:
dataset = pd.read_csv('reviews.csv',usecols=['review_id','review','category'])

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11321 entries, 0 to 11320
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review_id  11321 non-null  object
 1   review     11321 non-null  object
 2   category   10601 non-null  object
dtypes: object(3)
memory usage: 265.5+ KB


In [4]:
dataset['category'].value_counts()

general          2969
usability        2155
effectiveness    1186
efficiency        918
enjoyability      909
cost              838
reliability       599
security          392
compatibility     357
learnability      127
safety             80
aesthetics         71
Name: category, dtype: int64

# Data Preprocessing

### Droping reviews with missing sentiment

In [5]:
dataset = dataset.dropna()

In [6]:
dataset.loc[7,'review']

'I’ve used Evernote daily since 2013 to journal, organize work streams and plan effective projects. I often joke that it is my external brain because the way I have it categorically organized encompasses most facets of my life. The flexible hierarchy available thru notes, notebooks and tags works well for me. Syncing across devices was also a game changer for me. Truthfully, my biggest fear is that Evernote would ever go away! Please don’t. Yours could forever, Evernote. 💌'

### Cleaning reviews 

#### Converting emojis and emoticons to text

In [7]:
pip install emot --upgrade

Requirement already up-to-date: emot in e:\anacondauser\lib\site-packages (3.1)
Note: you may need to restart the kernel to use updated packages.


In [8]:
dataset.loc[7,'review']

'I’ve used Evernote daily since 2013 to journal, organize work streams and plan effective projects. I often joke that it is my external brain because the way I have it categorically organized encompasses most facets of my life. The flexible hierarchy available thru notes, notebooks and tags works well for me. Syncing across devices was also a game changer for me. Truthfully, my biggest fear is that Evernote would ever go away! Please don’t. Yours could forever, Evernote. 💌'

In [9]:
from emot.emo_unicode import UNICODE_EMOJI
def convert_emoji(text):
    for emot in UNICODE_EMOJI:
        text = text.replace(emot, "_".join(UNICODE_EMOJI[emot].replace(",","").replace(":","").split()))
    return text

In [10]:
dataset['review'] = dataset['review'].apply(convert_emoji)

In [11]:
dataset.loc[7,'review']

'I’ve used Evernote daily since 2013 to journal, organize work streams and plan effective projects. I often joke that it is my external brain because the way I have it categorically organized encompasses most facets of my life. The flexible hierarchy available thru notes, notebooks and tags works well for me. Syncing across devices was also a game changer for me. Truthfully, my biggest fear is that Evernote would ever go away! Please don’t. Yours could forever, Evernote. love_letter'

In [12]:
dataset.loc[128,'review']

'Hello, I’d like word in computer, you create a document, and you print it, I mean the basic. On mobile..nope. It’s like paint but blue themed. I mean there can be a lot of improvements and fixes. Also the app crashed my tablet like 3 times before even finishing the download. Ok other then that, I honestly didn’t like it. For a document it’s good you got the basics. But it isn’t enough like... ok maybe on my phone it might be bad and all that but i mean meh. But on the tablet (seeing the pictures in the App Store) it’s good I mean the same for computer but a little bit laggy and bugs and crashes. There can be a LOOT of différents if you could just work on it better.Ok. As an app. I can say meh. Not bad. Just less settings in the mob and tabs. But other then that crashes. Fix these and make the layout better :) also the app takes a lot to download and a lot to start it up. Make this a generator instead of a non deleting paper for like ever. Thanks for reading'

In [13]:
from emot.emo_unicode import EMOTICONS_EMO
def convert_emoticons(text):
    for emot in EMOTICONS_EMO:
        text = text.replace(emot, "_".join(EMOTICONS_EMO[emot].replace(",","").split()))
    return text

In [14]:
dataset['review'] = dataset['review'].apply(convert_emoticons)

In [15]:
dataset.loc[128,'review']

'Hello, I’d like word in computer, you create a document, and you print it, I mean the basic. On mobile..nope. It’s like paint but blue themed. I mean there can be a lot of improvements and fixes. Also the app crashed my tablet like 3 times before even finishing the download. Ok other then that, I honestly didn’t like it. For a document it’s good you got the basics. But it isn’t enough like... ok maybe on my phone it might be bad and all that but i mean meh. But on the tablet (seeing the pictures in the App Store) it’s good I mean the same for computer but a little bit laggy and bugs and crashes. There can be a LOOT of différents if you could just work on it better.Ok. As an app. I can say meh. Not bad. Just less settings in the mob and tabs. But other then that crashes. Fix these and make the layout better Happy_face_or_smiley also the app takes a lot to download and a lot to start it up. Make this a generator instead of a non deleting paper for like ever. Thanks for reading'

#### Replace a sequence of repeated characters with two characters

In [16]:
dataset.iloc[-1,1]

"I love Monopoly and when this game is working it is soooooooooo much fun. But it freezes way too often. If it was simply a free game with in App Purchases, I would not mind at all. But I pay for the fastest fiber optics network around, and even with that connection I can't normally make it through an online game. Every time I try it freezes at some point and I can't continue playing. For a game you have to pay $4 just to play normally, I really think that's a factor that needs to be addressed. But Pass and Play is a fun way to pass time when you're traveling with someone or are waiting on an appointment, and playing the AI can still be a fun experience as well. But please for the price you charge get the online play feature tuned up. Even if you toned down the graphics to decrease the chance of it freezing I'm sure people would still love to play!"

In [17]:
pattern = re.compile(r'(.)\1*')  
def reduce_sequence_word(word):
     return ''.join([match.group()[:2] if len(match.group()) > 2 else match.group() for match in pattern.finditer(word)]) 
def reduce_sequence_review(review):
     return ' '.join([reduce_sequence_word(word) for word in review.split(' ')])  

In [18]:
dataset['review'] = dataset['review'].apply(reduce_sequence_review)

In [19]:
dataset.iloc[-1,1]

"I love Monopoly and when this game is working it is soo much fun. But it freezes way too often. If it was simply a free game with in App Purchases, I would not mind at all. But I pay for the fastest fiber optics network around, and even with that connection I can't normally make it through an online game. Every time I try it freezes at some point and I can't continue playing. For a game you have to pay $4 just to play normally, I really think that's a factor that needs to be addressed. But Pass and Play is a fun way to pass time when you're traveling with someone or are waiting on an appointment, and playing the AI can still be a fun experience as well. But please for the price you charge get the online play feature tuned up. Even if you toned down the graphics to decrease the chance of it freezing I'm sure people would still love to play!"

#### Removing non alphabetic words, stop words and  word stemming

In [20]:
import re
import nltk
nltk.download('stopwords')
#nltk.download('wordnet')
from nltk.corpus import stopwords
# This is stemming
from nltk.stem.porter import PorterStemmer
#this is lemmatization
#from nltk.stem import WordNetLemmatizer
stopwords_to_consider = []
stopwords_to_consider = ['on','off','no','nor','not',"don't",'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]
def text_preprocessor(review):
    processed_r = re.sub('[^a-zA-z]',' ',review)
    processed_r = processed_r.lower()
    processed_r = processed_r.split()
    all_stopwords = [w for w in stopwords.words('english') if not w in stopwords_to_consider]
    # This is stemming
    ps = PorterStemmer()
    processed_r = [ps.stem(word) for word in processed_r if not word in set(all_stopwords)]
    #this is lemmatization
    #lemmatizer = WordNetLemmatizer()
    #processed_r = [lemmatizer.lemmatize(word) for word in processed_r if not word in set(all_stopwords)]
    return ' '.join(processed_r)
    

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [21]:
dataset['review'] = dataset['review'].apply(text_preprocessor)

In [22]:
dataset = dataset[dataset['review'].str.len() > 20]

In [23]:
dataset.head(5)

review_id  \
0  c9274c0a-a120-4e09-816b-7a8ba3a16634   
2  506230e3-cc98-4233-be40-89e52d53990c   
3  69d44a5e-218f-4f55-8a99-6cca55d43ca1   
4  3d0b634c-d402-47e8-ba7d-bf6209fed826   
5  7310f23f-06c2-447d-aafd-81b29765169d   

                                              review       category  
0  new version thing entir differ aesthet thing t...      usability  
2  lot peopl use word standard run problem use ev...        general  
3  origin skeptic on pay on todo list app come re...  effectiveness  
4  use go app note take year problem write use re...           cost  
5  use year tag capabl uniqu integr across platfo...      usability

In [24]:
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [25]:
X

array([['new version thing entir differ aesthet thing thing much minimalist thing seem lot ui bloat not quit sure design award came'],
       ['lot peopl use word standard run problem use everi updat problem format everyth on page partli on page on part partli on page forth throughout page document tri call support reach someon bare speak english tell happen say chang someth document ye close document yesterday format correctli updat app today open wrong must middl night switch appl page thank peopl work realli hard make work realli great effort part not fun issu happen on macbook ipad point set someth exactli want simpl updat chang everyth nonsens'],
       ['origin skeptic on pay on todo list app come realiz great invest abl creat mani differ header project categor differ class take no longer use physic planner app take care problem eas use simplic great function led rate app star definit worth price'],
       ...,
       ['game great pass time line wait place order favorit dinner re

### Label encoding the dependent variable

In [26]:
y

array(['usability', 'general', 'effectiveness', ..., 'efficiency', 'cost',
       'enjoyability'], dtype=object)

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [28]:
print(le.classes_)
print(y)

['aesthetics' 'compatibility' 'cost' 'effectiveness' 'efficiency'
 'enjoyability' 'general' 'learnability' 'reliability' 'safety' 'security'
 'usability']
[11  6  3 ...  4  2  5]


### Creating the Bag of Words model

In [29]:
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.feature_extraction.text import TfidfVectorizer
preprocess = ColumnTransformer(transformers=[('vectorize', TfidfVectorizer(ngram_range=(1,5),max_features = 7000),0)],remainder='passthrough')
X = preprocess.fit_transform(X).toarray()

In [30]:
len(X[0,:])

7000

### Spliting dataset

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=1)

In [32]:
X_train


array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.1494523, 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]])

In [33]:
y_train

array([ 5, 11,  4, ...,  4,  8, 11])

# Classification 

### Training model - Naive Bayes

In [34]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

### Result evaluation

In [35]:
y_pred = classifier.predict(X_test)

##### Accuracy and confustion matrix

In [36]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm =confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print(cm)
print("The accuracy of model is: {:0.2f}".format(accuracy*100))

[[  5   0   5   1   0   2   0   5   2   1   2   0]
 [  0  23   7   2   6   0   3   0   2   0   1  49]
 [ 10  11  59  16   5  31   6  15   9   6  12  53]
 [  4  27  12  15  17  12   9   8  12  10  30 120]
 [  5  21  17   8   8  20  11   9  14   7  16 103]
 [ 25   0  45   2   3  35   7  33  23  18  13  14]
 [ 46  32  76  28  27  80  37  56  41  32  59 223]
 [  3   0   6   0   0   7   0   8   1   1   5   0]
 [  6   7  12   5   8   9   2  11  12   7   7  49]
 [  0   1   1   0   1   5   1   2   3   0   4   1]
 [  0   1   2   2   3   4   4   4   6   5  32  29]
 [  0  60  22  23  46   3  21   0  11   2  38 326]]
The accuracy of model is: 21.15


##### KFold Cross Validation

In [37]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("The Average Accuracy of model is: {:.2f} %".format(accuracies.mean()*100))
print("With a Standard Deviation of: {:.2f} %".format(accuracies.std()*100))

The Average Accuracy of model is: 22.27 %
With a Standard Deviation of: 1.35 %


### Training model - Kernel SVM

In [38]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

### Result evaluation

##### Accuracy and confustion matrix

In [39]:
y_pred = classifier.predict(X_test)

In [40]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm =confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print(cm)
print("The accuracy of model is: {:0.2f}".format(accuracy*100))

[[  0   0   1   1   0   6  15   0   0   0   0   0]
 [  0  10   3   5   3   0  18   0   0   0   0  54]
 [  0   3  50   4   2  18 109   0   1   0   3  43]
 [  0   4   5  12   8  11  92   0   3   0   7 134]
 [  0   3   7   8  11   4  86   0   8   0   3 109]
 [  0   0  11   2   2  31 151   0   9   0   2  10]
 [  0   5  27  21  13  51 394   0   7   0   8 211]
 [  0   0   2   1   1   5  22   0   0   0   0   0]
 [  0   0   6  11   4   9  56   0   5   0   2  42]
 [  0   0   0   0   1   3  11   0   1   0   1   2]
 [  0   0   1   3   1   0  29   0   1   0  22  35]
 [  0   8  12  36  16   2 128   0   3   0   6 341]]
The accuracy of model is: 33.08


##### KFold Cross Validation

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("The Average Accuracy of model is: {:.2f} %".format(accuracies.mean()*100))
print("With a Standard Deviation of: {:.2f} %".format(accuracies.std()*100))

#### Precision recall and f-measure

In [ ]:
from sklearn.metrics import precision_score,recall_score,f1_score
p_score = precision_score(y_test,y_pred)
r_score = recall_score(y_test,y_pred)
f_score = f1_score(y_test,y_pred)
print("The precision of model is: {:0.2f}".format(p_score*100))
print("The recall of model is: {:0.2f}".format(r_score*100))
print("The f-measure of model is: {:0.2f}".format(f_score*100))